### ISSUE TITLE
When resolving to stdout do not display status

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/weaver#184]
**Describe the bug**
When the output is stdout, the status lines (example below) will break any kind of stream processing, such as passing it to `jq`.

example:
```
✔ SemConv registry loaded (111 files)
✔ No policy found
✔ SemConv registry resolved
```

**To Reproduce**
1. Run `weaver registry resolve -f json | jq .`
2. watch it fail because of the status printed at the beginning

**Expected behavior**
The resolve output should be in the correct format, free of any status outputs.  

**Additional context**
These statuses are nice if we are outputting to a file or if they were on stderr.

**Comment by lquerel** [comment]
`--quiet` is no longer required with #187 (not yet approved at this point of time).

**Comment by MadVikingGod** [comment]
Is there any way to promote this option to A) show up in the `weaver registry resolve --help`, and B) Be usable from the end of the command?

For B) `weaver --quiet registry resolve` works, but `weaver registry resolve --quiet` does not.

**Comment by lquerel** [comment]
Yes, it's definitely something to improve in the user experience. We use Clap for command-line parsing, and while there are some limitations, there are workarounds to ensure that both A and B are feasible.

**Comment by lquerel** [comment]
@MadVikingGod with #187 merged `--quiet` is no longer required. 

However, I'd like to keep this issue open as I will make some changes to accept the `--quiet` argument in a more discoverable position.

**Comment by lquerel** [comment]
Fixed in #196 (pending approval).

**Comment by jerbly** [comment]
@lquerel - this is not fixed. We have a general problem with the separation of artifacts from diagnostics when using stdout. Most registry commands can now produce an artifact to stdout for downstream consumption e.g `resolve`, `diff`, `stats`, `json-schema`, `live-check`.

To cleanly separate artifacts from diagnostics we could send diagnostics to `stderr`. This means that `weaver registry resolve -f json | jq .` works AND shows you warnings from the diagnostics.

I believe this is a neat solution for all registry commands and would make the code and behaviour consistent.

The trade-off here is that for `check` the diagnostic output is also the "artifact". So perhaps for this special case, we could add `--diagnostic-stdout` to override the default and switch diagnostics to stdout. And perhaps `check` always switches to this mode. (Note, the current Semantic Conventions Makefile does not use the output, only the exit-code).

WDYT?

**Comment by lquerel** [comment]
@jerbly I’ll have to look at this more closely, but I initially introduced the `--quiet` parameter for this purpose (with the associated `QuietLogger`). In what scenario does it not work?

**Comment by jerbly** [comment]
The logging is not the issue, `--quiet` does indeed suppress output from the logger.

This is for DiagnosticMessages. Try this command: `cargo run -- registry resolve -r crates/weaver_resolver/data/registry-test-11-prefix-refs-extends -f json | jq .` - there are only Warnings in the DiagnosticMessages so shouldn't fail. We can just hide the Warnings of course but what if I want to see them?
